### ISSUE TITLE
"New Password" and "Confirm Password" fields not appearing when reset link is opened in Chrome

### ISSUE THREAD

**Issue by abdullah117765** [Invotyx/horilla#9]
**Title:**
"New Password" and "Confirm Password" fields not appearing when reset link is opened in Chrome

**Summary:**
After initiating the **Forgot Password** process and receiving the reset link via email, the link works correctly when opened in **Microsoft Edge**, displaying the fields for **New Password** and **Confirm Password**. However, when the same link is copied and opened in **Google Chrome**, only the field labels appear without any input boxes, making it impossible to reset the password.

**Steps to Reproduce:**

1. Click on **"Forgot Password"** on the login screen.
2. Enter a valid email address and submit the request.
3. Open the password reset link received via email:
   * Open the link directly from **Outlook (opens in Edge)** → works correctly.
   * Copy the same link and paste it into **Google Chrome** → issue occurs.
4. Observe the password reset screen in **Chrome**.

**Expected Result:**
Both **New Password** and **Confirm Password** input fields should be visible and functional in **all browsers**, including Chrome.

**Actual Result:**
In **Chrome**, only the labels **"New Password"** and **"Confirm Password"** are shown. Input fields are missing, preventing the user from resetting the password.

![Image](https://github.com/user-attachments/assets/e95ee742-5df2-43d6-84b8-b17c36b515d3)

**Comment by abdullah117765** [comment]
<img width="1901" height="1020" alt="Image" src="https://github.com/user-attachments/assets/a9d49ac6-1159-4d3d-8d1a-b7a26c9fb536" />

fixed

**Comment by Shakeel315** [comment]
Again facing the same issue

![Image](https://github.com/user-attachments/assets/510c6a40-2075-4628-8561-671856e4546b)

**Comment by abdullah117765** [comment]
kindly remove the caches as the browser  is using the old

**Comment by Shakeel315** [comment]
after clearing cache still facing same issue 

![Image](https://github.com/user-attachments/assets/3f14fabe-1a2b-4d7a-853b-5a817a84edf8)

**Comment by abdullah117765** [comment]
server issue, increase the computing power of the server
